### ISSUE TITLE
Bitcoin e la Blockchain

### ISSUE THREAD

**Issue by nicolaiarocci** [DevRomagna/eventi#1]
Propongo @erubboli come speaker 😁

**Comment by erubboli** [comment]
presente :)

**Comment by nicolaiarocci** [comment]
Grande Enrico. Potrebbe essere il primo talk di DevRomagna quindi sentiti onorato 😄 . Hai date disponibili verso fine aprile?

**Comment by nicolaiarocci** [comment]
E mi serve un titolo. Ne hai uno "ufficiale" o faccio io?

**Comment by nicolaiarocci** [comment]
@erubboli il talk è programmato: https://www.meetup.com/it-IT/DevRomagna/events/238853473/
