### ISSUE TITLE
D3.js - Data visualization

### ISSUE THREAD

**Issue by verlok** [DevRomagna/eventi#21]

**Comment by MaxArt2501** [comment]
Ho cominciato a preparare questo talk, mettete i like come see fosse feisbúc! 👍
#hashtag

**Comment by nicolaiarocci** [comment]
@MaxArt2501 sei ancora disponibile per questo talk? Che mese prefereisci nel periodo da gennaio a maggio?

**Comment by MaxArt2501** [comment]
Sì, sono sempre disponibile. Direi che orientativamente potrei prepararlo già per gennaio/febbraio.

**Comment by nicolaiarocci** [comment]
@MaxArt2501 avresti eventualmente anche una location per questo talk, diciamo il 18 Ottobre?

**Comment by MaxArt2501** [comment]
Ciao, questa notizia arriva un po' all'improvviso 😅
In questo periodo stiamo eseguendo lavori di adeguamento degli spazi, quindi la disponibilità è cambiata. L'intenzione di ospitare l'evento comunque c'è senza dubbio.
Si potrebbe riprogrammare il talk per gennaio? Per il 18 ottobre sarei anche molto stretto con la presentazione.

**Comment by nicolaiarocci** [comment]
ok allora lo programmiamo per Gennaio. Se intanto mi mandi abstract e tuo profilo lo pubblichiamo su meetup (17 gennaio)

**Comment by nicolaiarocci** [comment]
@MaxArt2501 mi confermi per favore data e ospitalità oltre a mandarmi il to profilo

**Comment by MaxArt2501** [comment]
17 gennaio è ok, abbiamo la disponibilità qui presso Antreem.
Quanto prima ti mando l'abstract e il profilo 👍 
Te li mando per email?

**Comment by nicolaiarocci** [comment]
Yes, va bene nicola at nicolaiarocci punto com

**Comment by nicolaiarocci** [comment]
@MaxArt2501 abstract e profilo!

**Comment by MaxArt2501** [comment]
# Data visualization con D3.js

## Abstract

I grafici sono un aspetto importante per un buon impatto visivo di un'applicazione web. E per essi esistono svariate librerie, ma non sempre è così facile... Perché a volte si vorrebbe un'impostazione, un effetto, una colorazione che proprio non si riesce a fare, o magari ci porterebbe ben oltre la solita regola dell'80-20.
E allora il riferimento, dal "lontano" 2011, è sempre quello: D3.js, la libreria che ci garantisce performance e massima flessibilità, ereditando i concetti più avanzati dei framework di front-end e applicandoli all'idea di "Data Driven Document".
Vedremo i concetti alla base della libreria, il loro utilizzo all'atto pratico, le tecniche di manipolazione dati fino all'integrazione con le più moderne librerie di sviluppo front-end, quali React e Angular.

## Bio

Sviluppatore e architetto web presso Antreem, appassionato di sviluppo, scienza e tecnica. Curioso della piattaforma web. Non pensa che reinventare la ruota sia del tutto inutile. Ogni domenica fa i bagni nel fango insieme a 14 compagni di squadra. 🏉

**Comment by nicolaiarocci** [comment]
https://www.meetup.com/it-IT/DevRomagna/events/256601308/
