### ISSUE TITLE
Jest - Painless Javascript Testing

### ISSUE THREAD

**Issue by nicolaiarocci** [DevRomagna/eventi#3]
Nemmeno 24 ore dopo il lancio del meetup abbiamo già un evento programmato (per domani!): 
https://www.meetup.com/it-IT/DevRomagna/events/238796165/

**Comment by sensorario** [comment]
Ed una volta che un evento si e' concluso? Chiudiamo la issue e basta?

**Comment by nicolaiarocci** [comment]
Grazie agli amici di [Studio Mado](http://www.studiomado.it) per averci ospitato! 

![minompi_2017-mar-30](https://cloud.githubusercontent.com/assets/512968/24537588/ab445d8a-15e3-11e7-826a-b5a196ccd50c.jpg)

**Comment by nicolaiarocci** [comment]
@sensorario sì l'idea è anche che se ci sono state slide o altri contenuti questi possano essere aggiunti a questo repository, sotto forma di pull request.
