### ISSUE TITLE
Anxiety Driven Development (unconference - inspirational)

### ISSUE THREAD

**Issue by Fuminshou** [DevRomagna/eventi#32]
Sviluppare in una situazione di ansia non è facile, non è produttvo ma soprattutto non è piacevole!
In 15 minuti (perchè oltre mi viene l'ansia) vi parlerò della mia personale esperienza e di qualche trucchetto per cercare di gestire l'ansia... perchè se non possiamo uscire dal tunnel almeno cerchiamo di arredarlo!

**Comment by nicolaiarocci** [comment]
@Fuminshou che ne dici di organizzare per Luglio? Vista la stagione estiva sarebbe carino fare una cosa in spiaggia o dintorni: birretta, quattro chiacchiere e il tuo intervento che non essendo lungo si sposa bene con questa situazione.

**Comment by AlessandroMinoccheri** [comment]
Ottima idea spiaggia + birra + devRomagna che vuoi di piu? 👍

**Comment by sensorario** [comment]
Ma io son in Giappone!!!

**Comment by Fuminshou** [comment]
Se si tratta di organizzare una serata ok, l'idea mi piace, ma non so se sono fisicamente presente per parlare, luglio per me è un mese critico :/

**Comment by nicolaiarocci** [comment]
Allora rinviamo, non c'è problema: lo sapevo che Luglio era una rogna :-)

**Comment by nicolaiarocci** [comment]
@Fuminshou che mese preferisci per questo talk, nel periodo da dicembre a maggio?

**Comment by Fuminshou** [comment]
Se fosse possibile gennaio sarebbe perfetto, così mi tolgo il pensiero, ma da gennaio ad aprile ci sono sempre (ad oggi il calendario trasferte è vuoto)

**Comment by sensorario** [comment]
I due piu' votati, e con speaker, sono questo intervento e quello sui chatbots: https://github.com/DevRomagna/eventi/issues/52

Perl'incontro di dicembre che cosa si fa?

**Comment by Fuminshou** [comment]
C'è la proposta ["Frameworkless frontend developer"](https://github.com/DevRomagna/eventi/issues/60) che si può fare solo a dicembre o gennaio, ha solo tre voti ma forse è il caso di valutarla lo stesso visto la disponibilità limitata (io bene o male ci posso essere sempre)

**Comment by nicolaiarocci** [comment]
Putroppo pochissimi votano, in generale.

**Comment by nicolaiarocci** [comment]
@Fuminshou Facciamo a Gennaio questo, presso Ideato?

**Comment by Fuminshou** [comment]
@nicolaiarocci in ideato facciamo già phptestfest a dicembre e (se si fa) ospitiamo il talk su Frameworkless frontend developer che si può fare solo a dicembre o gennaio.
Per noi non è un problema, ma non vorrei infilare troppi eventi nello stesso posto e penalizzare altre location

**Comment by nicolaiarocci** [comment]
Sì hai ragione, questo lo riprogrammiamo più avanti.

**Comment by nicolaiarocci** [comment]
Allora direi che questo è il più votato assieme al #66 e potremmo farli assieme. Giovedi 18 Ottobre che ne dite?

**Comment by nicolaiarocci** [comment]
Sarebbe anche interessante ripartire in una nuova location... qualcuno la mette a disposizione?

**Comment by verlok** [comment]
Io per #66 il 18 ottobre ci posso essere. 
Fatemi sapere con il mention @ altrimenti non mi arrivano le mail

**Comment by Fuminshou** [comment]
@nicolaiarocci @verlok 
Il 18 sono al SymfonyDay a Verona (probabilmente partirò il giorno prima)
Vi anticipo già che la settimana dopo sono via dal martedì al venerdì.
Posso organizzarmi per fine novembre, Codemotion permettendo

**Comment by davidegiunchi** [comment]
> Sarebbe anche interessante ripartire in una nuova location... qualcuno la mette a disposizione?

@nicolaiarocci come FoLUG possiamo dare disponibilità della nostra sede per una o più serate: [https://www.folug.org/sede/](https://www.folug.org/sede/) , che si trova appunto a Forlì, nello specifico a Vecchiazzano.
Nella sede c'è una sala grande che utilizziamo per corsi/conferenze&c, essendo però uno spazio condiviso da varie associazioni, bisogna prenotarlo con anticipo, ho quindi bisogno di avere 2-3 date da sottoporre ai gestori, in modo da selezionare una serata libera.
Abbiamo il proiettore.
Difianco alla sala c'è anche una pizzeria, quindi è ideale se volete fare una pizzata pre-evento.
Fammi sapere se interessa
ciao

**Comment by nicolaiarocci** [comment]
@davidegiunchi grazie Davide.

@Fuminshou @verlok che ne dite allora del 15 Novembre?

**Comment by Fuminshou** [comment]
@nicolaiarocci @verlok il 15/11 ci sono
fra l'altro abito proprio a forlì :D :D :D

**Comment by nicolaiarocci** [comment]
@davidedonattini il 15 novembre andrebbe bene per FoLUG? @verlok per te la data è ok?

**Comment by verlok** [comment]
15 novembre andrebbe bene per me. Non troppo presto, prendo il treno alle 18:35 da Bologna.

**Comment by nicolaiarocci** [comment]
ok aspettiamo conferma da @davidedonattini e poi lo accendiamo.

**Comment by davidedonattini** [comment]
Ciao @nicolaiarocci penso ci sia un errore di mention, rigiro a @davidegiunchi

**Comment by nicolaiarocci** [comment]
giusto!

**Comment by davidegiunchi** [comment]
@nicolaiarocci purtroppo in questi giorni si sono verificati dei problemi con la sede, non posso quindi darvi la certezza che il luogo sia disponibile per il 15 dicembre.
Scusate, mi rifarò vivo quando lo spazio tornerà fruibile.

**Comment by nicolaiarocci** [comment]
@davidegiunchi in realtà si parlava del 15 novembre. Qualcun altro offre disponibilità locali?

**Comment by verlok** [comment]
@davidedonattini chiedo: Studio Mado il 15 novembre sarebbe disponibile?

**Comment by davidegiunchi** [comment]
> 
> 
> @davidegiunchi in realtà si parlava del 15 novembre. Qualcun altro offre disponibilità locali?

Sì, mi sono sbagliato a scrivere, intendevo il 15 novembre

**Comment by davidedonattini** [comment]
> @davidedonattini chiedo: Studio Mado il 15 novembre sarebbe disponibile?

@verlok per noi il 15 novembre è ok

**Comment by nicolaiarocci** [comment]
Abbiamo ben 2 speaker, la location, la data... la accendiamo. Grazie @davidedonattini

**Comment by nicolaiarocci** [comment]
@verlok @Fuminshou mi mandate mini abstract e vostro profilo che volete vedere sulla pagina meetup? Come abstract posso anche usare quel che avete messo in testa ai 2 ticket se volete.

**Comment by nicolaiarocci** [comment]
![image](https://user-images.githubusercontent.com/512968/46352632-91300600-c65a-11e8-91dc-032c5aa437a2.png)

Mandatemi aggiornamenti per le bio e/o abstract se volete, fine settimana pubblico!

**Comment by verlok** [comment]
**Abstract**

Ti sarà capitato almeno una volta di parlare o di fare una presentazione ad un gruppo di persone, sia esso composto dalle persone del tuo team od una platea più vasta di sconosciuti. 

Durante questo micro-talk vedremo in sintesi come si struttura una presentazione, come si espone, a cosa prestare attenzione, verranno proiettati video semiseri di esempi virtuosi, e verrà dato qualche consiglio su cosa fare e cosa non fare, con qualche esercizio pratico alla fine.

**Bio**

Front-end architect a YOOX NET-A-PORTER, orgoglioso creatore e manutentore di [vanilla-lazyload](https://github.com/verlok/lazyload) e speaker occasionale. Appassionato di web performance, user experience e l'accessibilità, nella vita è un papà ecosostenibile amante del buon cibo e delle biciclette.

**Comment by nicolaiarocci** [comment]
@verlok aggiornato,grazie.

@Fuminshou per te va bene così il bio/abstract?

**Comment by Fuminshou** [comment]
Sorry @nicolaiarocci ero in ferie 😀 

Comunque va bene quello che avete utilizzato, grazie!

**Comment by verlok** [comment]
@AlessandroMinoccheri @sensorario ci siete stasera? Se no, siateci! 💃 

Grazie @nicolaiarocci per l'aggiornamento della [pagina su Meetup](https://www.meetup.com/it-IT/DevRomagna/events/255195925/)

**Comment by AlessandroMinoccheri** [comment]
Purtroppo non penso di esserci, forse riesco a rimanere giusto per un saluto :( @verlok

**Comment by verlok** [comment]
Ecco a voi, per chi c'era e per chi non c'era, le mie slide.
https://docs.google.com/presentation/d/1a9wd_pcQD9V_2eveM68dGOBwaJUC7qkPe6FDLcw5Qis/

**Comment by verlok** [comment]
Ciao a tutti,
mi piacerebbe avere il vostro feedback sul mio talk di ieri sera. 

Si tratta di dare un voto da 1 a 5 e - solo se volete - aggiungere cosa vi è piaciuto e cosa no.

> [Invia il tuo feedback](https://goo.gl/forms/3dVSnMADFh9R8SQy1)

Grazie

**Comment by nicolaiarocci** [comment]
Grazie Andrea e Nicole per i vostri interventi. Belli, divertenti, utili 👍

**Comment by nicolaiarocci** [comment]
https://www.meetup.com/it-IT/DevRomagna/events/255195925/

**Comment by MG55** [comment]
@Fuminshou è possibile avere anche le tue slide?

**Comment by Fuminshou** [comment]
Ecco qua le slide del mio intervento: [Anxiety Driven Development](https://www.slideshare.net/NicoleBartolini/anxiety-driven-development-codemotion-rome-2018)
