### ISSUE TITLE
Codice di jest test

### ISSUE THREAD

**Issue by verlok** [DevRomagna/eventi#33]
Ciao @nicolaiarocci,
dove posso postare il (poco) codice che ho scritto ieri sera alla demo di Jest?

**Comment by nicolaiarocci** [comment]
Ciao @verlok intanto grazie per ieri sera! Direi fai una PR su questo repo e metti tutto in un folder che ha per nome il titolo dell'evento. Nella commit fai riferimento al ticket #3, così ci arrivano anche se partono dal ticket.

**Comment by sensorario** [comment]
Se hai intenzione di scrivere due righe in un blog linkalo qui ^_^!!

**Comment by verlok** [comment]
TODO: 

* pubblicare i file, 
* scrivere un blog post

Ce la posso fare

**Comment by sensorario** [comment]
Non sei costretto a fare nulla ^_^. Pero' se ti puo' dare una spinta, ... grazie al tuo talk sto iniziando a fare tdd con javascript.

**Comment by nicolaiarocci** [comment]
Grande Andrea! Vedere #39.
