### ISSUE TITLE
Git in trincea

### ISSUE THREAD

**Issue by nicolaiarocci** [DevRomagna/eventi#34]
Trucchi e barbatrucchi. Best practices. Consigli sull'uso di git in progetti open source e condivisi di lungo periodo.

**Comment by sensorario** [comment]
Hai avuto anche esperienze con reflog?

**Comment by nicolaiarocci** [comment]
yep

**Comment by nicolaiarocci** [comment]
https://www.meetup.com/it-IT/preview/DevRomagna/events/240838433
