### ISSUE TITLE
Come creare un progetto open-source

### ISSUE THREAD

**Issue by verlok** [DevRomagna/eventi#4]

**Comment by nicolaiarocci** [comment]
Qui due o tre cose da dire le avrei :)

**Comment by nicolaiarocci** [comment]
aggiungerei anche "e come contribuire", che spesso è il primo passo per poi diventare a nostra volta autori.

**Comment by sensorario** [comment]
Io avrei qualche domanda sulla compilazione di file come 

 - CONTRIBUTING
 - UPGRADE-X.Y
 - CHANGELOG

**Comment by AlessandroMinoccheri** [comment]
Sarebbe carino capire anche "come mantenere" un progetto open source, le varie release, nuovi collaboratori, issue, pull requests...

**Comment by nicolaiarocci** [comment]
Ottimo!

**Comment by sensorario** [comment]
@nicolaiarocci potremmo fissare gia' la data di maggio con il tuo talk?

**Comment by sensorario** [comment]
@nicolaiarocci o @Fuminshou: i vostri sono a parimerito. Fate pari e dispari ^_^

**Comment by Fuminshou** [comment]
@sensorario @nicolaiarocci il mio talk è molto breve (15 min), potrebbe aver senso farlo in una serata con un altro talk breve oppure slittarlo alla prossima data così lo amplio un po' :)

**Comment by AlessandroMinoccheri** [comment]
Se poi ci scappano delle domande si potrebbe dilungare forse @Fuminshou . 
Potrebbe avere senso accoppiarlo con un talk di durata simile cosi potremmo fare due talk in una sera con spazio anche alle domande o nuovi spunti che ne dite?

**Comment by Fuminshou** [comment]
No ma non mi dovete fare domande che mi sale l'ansia 😁 
Scherzi a parte, è quello che dicevo anche io, possiamo accorparlo ad un altro talk quando ce ne sarà l'occasione, per riempire al meglio la serata @AlessandroMinoccheri 
Penso sia chiaro che a maggio lo farà @nicolaiarocci

**Comment by AlessandroMinoccheri** [comment]
Sono d'accordo con te! Potremmo anche inserire nelle varie proposte che sono state fatte se sono talk per una serata intera o no cosi magari riusciamo ad organizzare il tutto.

**Comment by sensorario** [comment]
Anche secondo me @AlessandroMinoccheri: https://github.com/DevRomagna/brainstorm/issues/2.

**Comment by Gsantomaggio** [comment]
bello! ci sto ! Aggiungerei anche qualche nota su come collaborare ad un progetto open-source non necesariamente legato al codice ma anche alla documentazione, stackoverflow, gruppi etc etc.! 
@nicolaiarocci

**Comment by nicolaiarocci** [comment]
https://www.meetup.com/it-IT/DevRomagna/events/239382597/

**Comment by Fuminshou** [comment]
@nicolaiarocci fammi sapere se per quella serata vi serve il proiettore e/o lavagna con fogli :)

**Comment by nicolaiarocci** [comment]
Proiettore sicuramente sì.
