### ISSUE TITLE
Introduzione a Docker

### ISSUE THREAD

**Issue by Christian961** [DevRomagna/eventi#41]
Potenzialità di Docker, clustering in ambiente Docker, creazione immagini, deploy, volumi e network in ambito Docker.

**Comment by AlessandroMinoccheri** [comment]
Ottimo!

**Comment by Fuminshou** [comment]
@Christian961 questa è una delle proposte più votate, quando saresti disponibile a fare il talk?
La prossima data libera è ad aprile (giovedì 19 da calendario), riusciamo ad organizzarci?

**Comment by davidegiunchi** [comment]
Visto che questa proposta è ferma da mesi, se non ci sono novità da Christian, io do la mia disponibilità a trattare l'argomento in una serata.
Il titolo "Introduzione a Docker" va bene.

**Comment by Christian961** [comment]
Ciao Davide e tutti,
Si io ci sono, facciamo prima un punto della situazione?

**Comment by nicolaiarocci** [comment]
@Christian961 possiamo fare questo incontro a Maggio, ma dobbiamo trovare il luogo. Eviterei di tornare da Ideato che ci ha già ospitato tante volte quest'inverno. Qualcuno ha disponibilità? Non ho capito se Cristian ti proponi come speaker o meno. Nel caso posta qui un abstract e un tuo profilo, così ci mettiamo avanti coi lavori. Altrimenti lo stesso farà @davidegiunchi. La data potrebbe essere giovedì 17 o 25.

**Comment by nicolaiarocci** [comment]
Ok, visti i tempi ormai stretti decido d'ufficio di assegnare @davidedonattini a questo talk. Davide hai una location disponibile? In alternativa potrei sentire se qui a Ravenna si trova qualcosa. Data preferita tra le due proposte?

**Comment by davidedonattini** [comment]
Ciao @nicolaiarocci,
forse volevi assegnarlo a @davidegiunchi 
Io però poso mettere a disposizione Studio Mado senza problemi.
Meglio il 25 come data.
Attendo vostra conferma.

**Comment by nicolaiarocci** [comment]
Ah certo scusami, maledetto autocomplete :-) @davidegiunchi il talk è tuo.

Grazie per la disponibilità di Studio Mado. Sentiamo @davidegiunchi se è disponibile per quella data e quella sede (alla fine l'errore magari torna utile)

**Comment by davidegiunchi** [comment]
Anch'io preferisco il 25 maggio, Studio Mado va benissimo, grazie @davidedonattini .
Come titolo del talk lascio "Introduzione a Docker", @nicolaiarocci l'abstract te lo mando tra qualche giorno. Ciao

**Comment by nicolaiarocci** [comment]
Ok aspetto abstract e tuo profilo per pubblicare evento su meetup. Prima è meglio è.

**Comment by davidegiunchi** [comment]
@nicolaiarocci 
**Abstract:**
I container, ed in particolare Docker, sono uno dei tormentoni IT più diffusi da 5 anni a questa parte.
In questa serata faremo una rapida analisi delle tecnologie utilizzate da Docker, per capire come funziona e come differisce da una VM.                   
Passeremo poi all'installazione di Docker su Windows e Linux, come utilizzarlo con gli argomenti più comuni della sua command line, come utilizzare immagini già presenti nell'hub, modificarle per le nostre esigenze e pubblicarle su un registry privato.
Infine valuteremo alcuni consigli, best-practice e vedremo come "l'ecosistema container" si sta evolvendo in questi ultimi anni.

**Profilo:**
Davide Giunchi. Abito a Forlì e faccio il Sysadmin da quando Linux era un sistema operativo di niccha.
Ho lavorato per aziende di vario tipo e dimensione, sempre focalizzandomi su Linux ed il Web, portando con me la passione per il Software Libero.
Negli ultimi anni mi sono avvicinato alle metodologie DevOps, cercando di migliorare e velocizzare la collaborazione con sviluppatori PHP e Python.
https://giunchi.net/
https://www.linkedin.com/in/davidegiunchi

@davidedonattini posso portare un proiettore

**Comment by nicolaiarocci** [comment]
https://www.meetup.com/it-IT/DevRomagna/events/250403502/

**Comment by davidegiunchi** [comment]
@davidedonattini mi servirebbe una connessione ad internet (wifi o cablata), mi è sufficente che verso l'esterno siano aperte le porte http/https e la 22 (ssh per il vps). 
Confermo che porterò il proiettore. 
Se per te va bene, cercherò di essere lì 20 min prima dell'inizio, per preparare pc&c.
grazie

**Comment by davidedonattini** [comment]
@davidegiunchi ottimo, non c'è problema, ti aspettiamo!

**Comment by nicolaiarocci** [comment]
Materiali: https://github.com/DevRomagna/eventi/tree/master/20180525-Inotroduzione-a-docker
