### ISSUE TITLE
Quindi quando sarà il prossimo evento?

### ISSUE THREAD

**Issue by verlok** [DevRomagna/eventi#42]

**Comment by AlessandroMinoccheri** [comment]
Noi Lunedi valutiamo se è gia pronta la nuova sala riunioni, se fosse già tutto ok proporrei a breve un  nuovo evento se nessun altro si fa avanti prima

**Comment by nicolaiarocci** [comment]
Allora, su Ravenna ho un paio di possibili location che dovrei finalizzare settimana prossima. Per il 27 Aprile (+ o -) dovremmo fare data con @erubboli su Bitcoin (#1) perché lui c'è in quel periodo lì, quindi ne approfittiamo spudoratamente. Tutto ancora volatile ma diciamo con buona approssimazione. Sono via un paio di giorni per PyCon, poi mi do da fare.

**Comment by AlessandroMinoccheri** [comment]
Noi saremmo disposti gia questo giovedi ad ospitare una nuova serata! @nicolaiarocci

**Comment by nicolaiarocci** [comment]
@AlessandroMinoccheri dove? Imola o Faenza nuova sede?

**Comment by AlessandroMinoccheri** [comment]
Si siamo nella nuova sede a Faenza via Galileo Galilei 6 (dove c'è il centro commerciale Le Cicogne)

**Comment by nicolaiarocci** [comment]
Ok dammi un po' di info:
- posti disponibili
- orario
- cena/bevuta eventuale? pre/post meetup, e dove?

**Comment by nicolaiarocci** [comment]
@sensorario ci saresti già questo giovedì per git-flow e branching model?

**Comment by nicolaiarocci** [comment]
Altra cosa, visto che cominciano le feste di Pasqua a scuola giovedì e quindi magari qualcuno che vorrebbe partecipare sarà via con la famiglia, non sarebbe meglio fare settimana prossima?

**Comment by AlessandroMinoccheri** [comment]
Per quanto riguarda i posti direi una trentina, orario 19:30/20:00 cena qui con pizza presa in un posto vicino, 20:30/21:00 partenza dell'evento.
Per quanto riguarda la data, ora che ci penso è meglio la settimana prossima  come hai suggerito!

**Comment by nicolaiarocci** [comment]
Ok aspettiamo conferma disponibilità di Simone per Giovedì 20.4.2017.

**Comment by sensorario** [comment]
Confermo Giovedi 20.

**Comment by nicolaiarocci** [comment]
https://www.meetup.com/it-IT/DevRomagna/events/239110404/
