### ISSUE TITLE
git-flow e branching model

### ISSUE THREAD

**Issue by verlok** [DevRomagna/eventi#5]

**Comment by sensorario** [comment]
@nicolaiarocci mi candido come speaker.

**Comment by nicolaiarocci** [comment]
@sensorario eccellente!

**Comment by nicolaiarocci** [comment]
@sensorario mi dai un abstract un po' più preciso da mettere nella descrizione del meetup?

**Comment by sensorario** [comment]
# Git Flow, Branching Model e Versionamento Semantico

Nella prima parte racconcentrero' sopratutto `git flow` quale flusso di sviluppo ideato da Vincent Driessen, che descrive un branching model preciso costruito attorno al versioning semantico. In questa prima parte si parlera' in maniera approfondita anche di versionamento semantico. Al termine di questa prima parte verranno accennati altri branching model.

Nella seconda parte verra' analizzato meglio un caso reale di branching model prendendo ad esempio un software PHP open source.

**Comment by nicolaiarocci** [comment]
https://www.meetup.com/it-IT/DevRomagna/events/239110404/
