### ISSUE TITLE
Eventi Estivi

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [DevRomagna/eventi#53]
Sarebbe possibile organizzare gli eventi del DevRomagna anche in Luglio e Agosto sapendo che in ogni caso ci sarà meno affluenza per dare continuità al gruppo?

**Comment by nicolaiarocci** [comment]
Non so, sarebbe un peccato "sprecare" topic che potrebbero interessare a molti che poi non possono partecipare, no? Luglio forse sì, magari virandola in qualcosa di leggero tipo birra + spiaggia. In realtà ci ho provato col talk breve di @Fuminshou, ma non c'è in quel periodo. Agosto secondo me no. Che ne dite?

**Comment by sensorario** [comment]
Mi gioco la carta del code retreat.

**Comment by Fuminshou** [comment]
Passare dal 15 giugno al 21 settembre senza niente è un po' rischioso, quindi per me si potrebbe fare una serata a luglio, anche se ci fosse meno gente comunque restiamo attivi.

Bonus: agosto ha tantissimi giovedì, il terzo sarebbe la settimana di ferragosto, assolutamente da evitare... ma potremmo barare e organizzare qualcosa il giovedì 31, così da riattivarci per la serata di settembre

**Comment by AlessandroMinoccheri** [comment]
Diabolica!
Approvo

**Comment by nicolaiarocci** [comment]
@sensorario mi mandi abstract ecc per code retreat, incusa location (immagino studio mado)? Così stasera la annunciamo al meetup.

**Comment by sensorario** [comment]
Sto chiedendo per la disponibilita' perche' non so se ci lasciano la sede per una giornata intera. Nel frattempo copio qui la descrizione di che cosa sia un coderetreat direttamente da http://coderetreat.org/

"Coderetreat is a day-long, intensive practice event, focusing on the fundamentals of software development and design. By providing developers the opportunity to take part in focused practice, away from the pressures of 'getting things done', the coderetreat format has proven itself to be a highly effective means of skill improvement. Practicing the basic principles of modular and object-oriented design, developers can improve their ability to write code that minimizes the cost of change over time."

**Comment by nicolaiarocci** [comment]
Ieri sera su 29 persone iscritte ci sono presentati in 12 (me e speaker incluso). Secondo me è effetto estate (se non fossero stati interessati a Bitcoin non si sarebbero iscritti). Inoltre parlandone ieri sera coi presenti è emersa perplessità generale all'idea di voler partecipare a meetup a luglio/agosto, in particolar modo a evento giornaliero. Ripartiamo a Settembre e vedrete che la voglia di meetup sarà tanta da fare ancora pienoni come in primavera 😄
