### ISSUE TITLE
PHP Test Fest

### ISSUE THREAD

**Issue by Fuminshou** [DevRomagna/eventi#59]
Il GrUSP partecipa al PHP Test Fest (da settembre a dicembre) e offre una cassa della sua birra ai PUG che partecipano all'evento.

So che non siamo un gruppo verticalizzato sul PHP, ma ci interessa partecipare come PUG?

Ideato mette a disposizione la sede (Cesena) per una serata nel mese di **dicembre**.
Dal GrUSP chiedono conferma quanto prima per organizzarsi con le birre.

Tutte le info sull'evento qui: https://phptestfest.org/start/
I gruppi già attivi: https://phptestfest.org/groups/2017/

**Comment by DonCallisto** [comment]
Io parteciperei volentieri anche se sono delle Marche (e se non è lo stesso giorno di quello marchigiano, ammesso e non concesso che si riesca ad organizzare, potrei partecipare ad entrambi).

La domanda che faccio è però questa: abbiamo qualcuno che possa fare da mentor, ossia qualcuno che sa già bene come muoversi nell'ambito di queste dinamiche del phptestfest, oppure è necessario mettersi sotto e studiarne le modalità?

**Comment by Fuminshou** [comment]
Io non ho mai partecipato quindi per me è tutto da studiare.
Come referente c'è Matteo Beccati del GrUSP, sicuramente lo possiamo pingare per avere più informazioni.

**Comment by nicolaiarocci** [comment]
Ragazzi, come sapete PHP non è il mio mondo. Se c'è abbastanza interesse nessun problema a metterci lo zampino come DevRomagna, ma ci vuole qualcuno che si prenda in mano la gestione dell'intera faccenda.

**Comment by micc83** [comment]
Io avrei molto piacere di esserci ma purtroppo non riesco a dedicare tempo all'organizzazione dell'evento.

**Comment by AlessandroMinoccheri** [comment]
Se non ci sono imprevisti io parteciperei volentieri!

**Comment by Fuminshou** [comment]
Ho parlato con Matteo Beccati del GrUSP, mi ha detto che l'evento in una sola serata non si riesce a far l'evento (serve tempo per decidere cosa fare ed eventualmente dividersi in sottogruppi).
Gli altri PUG lo hanno fatto di sabato, potremmo farlo anche noi, dalle 10:30 alle 17:30 (o finchè si regge). Ideato conferma la disponibilità della sede.
Il giorno potrebbe essere il 2/12 (in contemporanea con devmarche così facciamo gruppo)

**Comment by nicolaiarocci** [comment]
@Fuminshou se mi mandi abstract, titolo, ecc., lo programmo.

**Comment by Fuminshou** [comment]
@nicolaiarocci 
Titolo: PHP TestFest Romagna
Abstract: 

> Hai sempre voluto contribuire al mondo PHP ma ti spaventava l'idea che le tue competenze non fossero sufficienti? Non c'è problema: diventa un contributor di PHP scrivendo test!
> L'evento si compone di tre fasi:
> 1. meeting introduttivo
> 2. sessione introduttiva su come scrivere test e contribuire al PHP TestFest
> 3. codice!
> 
> Sono previsti premi per le migliori submission individuali e di gruppo, i vincitori saranno annunciati a gennaio 2018!
> 
> Inoltre il GrUSP offre la birra di sua produzione a tutti i partecipanti all'evento ;)
> 
> Maggiori informazioni: [https://phptestfest.org/start/](https://phptestfest.org/start/)

Data: sabato 2/12
Luogo: ideato (piazza sanguinetti 106, cesena FC)
Ora: dalle 10:30 alle 17:30 (pranzo a carico dei partecipanti)

**Comment by nicolaiarocci** [comment]
https://www.meetup.com/it-IT/DevRomagna/events/245283762/?_locale=it-IT

@Fuminshou sei la coordinatrice 👍

**Comment by nicolaiarocci** [comment]
PS: ho messo 40 posti, so che ne avete probabilmente meno ma c'è sempre un drop (eventualmente fammi sapere che correggiamo)

**Comment by Fuminshou** [comment]
@nicolaiarocci no problem, essendo un hackaton ci mettiamo nelle postazioni degi vari uffici... se veramente raggiungiamo i 40 partecipanti in loco per un evento del genere mi tingo i capelli di rosa 😀 
grazie per l'evento!

**Comment by valentinavirga** [comment]
io ho gli occhi a cuoricino.

**Comment by Fuminshou** [comment]
@nicolaiarocci questo di può chiudere ;)
