### ISSUE TITLE
The Go programming language

### ISSUE THREAD

**Issue by verlok** [DevRomagna/eventi#6]

**Comment by sensorario** [comment]
Mi candido come speaker. Talk livello base.

**Comment by nicolaiarocci** [comment]
@sensorario abstract e profilo dello speaker, così lo programmiamo.

**Comment by sensorario** [comment]
ASAP!

**Comment by nicolaiarocci** [comment]
@sensorario hai l'ASAP lungo!

**Comment by sensorario** [comment]
Go è un linguaggio di programmazione open source sviluppato da Google. Nasce nel 2007 per soddisfare le esigenze di creare un linguaggio con una compilazione efficiente, di un'esecuzione veloce e di una facilità di programmazione. Annunciato ufficialmente nel novembre 2009, Go adotta una sintassi vicina al C eccetto per la dichiarazione dei tipi e per la mancanza di parentesi tonde nei costrutti for e if. Ha un sistema di garbage collection che si occupa autonomamente della gestione della memoria. Non include l'intercettazione di eccezioni, l'eredità dei tipi, la programmazione generica, le asserzioni e l'overloading dei metodi.

**Comment by nicolaiarocci** [comment]
Ottimo. Manca solo il tuo profilo 👍

**Comment by sensorario** [comment]
Preferisci il sinistro o il destro? :trollface:

**Comment by nicolaiarocci** [comment]
scemo

**Comment by nicolaiarocci** [comment]
@sensorario purtroppo sarò a Milano quella sera per GitHub Constellation. Fai tu gli onori di casa e pure il talk! Buona fortuna!

PS: ci sono sei persone in lista di attesa. Se pensi che Mado riesca ad ospitarle fammi sapere che allarghiamo la capienza, anche perchè tipicamente qualcuno di quelli iscritti non si presenta.

**Comment by sensorario** [comment]
@davidedonattini che dici? Apriamo i cancelli?

**Comment by sensorario** [comment]
@nicolaiarocci questo si dovrebbe chiudere
