### ISSUE TITLE
Frameworkless Frontend Development

### ISSUE THREAD

**Issue by francesco-strazzullo** [DevRomagna/eventi#60]
Ciao a tutti,
mi piacerebbe proporre questo talk in cui si parla di sviluppo frontend senza framework. Oltre ad un esempio di una piccola applicazione che non ha alcun tipo di dipendenza esterna, una parte consistente del talk tratta di come capire quando abbandonare i framework può essere una strada giusta per un team o per un progetto.

Ho già fatto questo talk al Codemotion Berlino e Milano, quindi trovate sia le [slides](https://slides.com/francescostrazzullo/frameworkless-frontend-development-codemotion-milan-2017/) che il [repo](https://github.com/e-xtrategy/frontend-frameworkless-development) github.

**Comment by nicolaiarocci** [comment]
@francesco-strazzullo hai anche a disposizione una sede dove incontrarci?

**Comment by francesco-strazzullo** [comment]
@nicolaiarocci Sì Ideato mi ospita senza problemi.

**Comment by nicolaiarocci** [comment]
@francesco-strazzullo ottimo Francesco. Ti va di traddurre l'abstract di Codemotion in Italiano? In alternativa lo metto in Inglese che va bene lo stesso. Mi serve anche data e ora, da concordare con gli amici di Ideato.

**Comment by Fuminshou** [comment]
Se vogliamo mantenere il 3 giovedì del mese abbiamo 21/12 oppure 18/01.

Se invece vogliamo valutare un calendario più ampio, ideato c'è tutte le sere da lunedì a giovedì, dall'8 dicembre al 21 e dall'8 gennaio in poi. Unico impegno per ora la cena aziendale del 19/12 (martedì).

Al netto di queste valutazione, @francesco-strazzullo decidi tu :)

**Comment by francesco-strazzullo** [comment]
@nicolaiarocci @Fuminshou  Per me il 18/01 andrebbe benissimo. Entro domani vi faccio trovare l'abstract in italiano!

**Comment by nicolaiarocci** [comment]
Anche io penso che il 18/01 sia perfetto. Grazie Francesco, aspettiamo il tuo abstract.

**Comment by francesco-strazzullo** [comment]
@nicolaiarocci Ecco l'abstract:
"Nello sviluppo Frontend a ogni nuovo progetto scegliamo il framework che in quel momento ci sembra il migliore, ma poi qualcosa si rompe. Con il passare del tempo ci accorgiamo che quel framework non risponde più alle esigenze e diventa più d’intralcio che d’aiuto! Durante il talk vedremo come poter sviluppare un'applicazione frontend senza alcun tipo di dipendenza esterna, ma soprtattutto capiremo quando può essere una strada utile al nostro progetto."

**Comment by nicolaiarocci** [comment]
https://www.meetup.com/it-IT/DevRomagna/events/245313829/
