### ISSUE TITLE
Perfezionare il public speaking  

### ISSUE THREAD

**Issue by verlok** [DevRomagna/eventi#66]
Ciao,
un paio danni fa ho fatto un corso di public speaking pagato dalla mia azienda. 

Dopo quel corso, ho tenuto un paio di talk ad un paio di conferenze mettendo in pratica gli insegnamenti e mi sono accorto della differenza, e credo anche il pubblico. 
Ma è altrettanto vero che continuo  vedere, in azienda e fuori, presentazioni fatte da relatori mediocri, con slide impossibili, e senza capo né coda. 

Mi piacerebbe riassumere in un’oretta quello che hanno detto a me.

**Comment by DonCallisto** [comment]
Interessante!

**Comment by verlok** [comment]
Ho già tenuto questo talk in azienda un paio di volte, e lo farò un altro paio di volte. In tutto ci vuole un’oretta piena, se ci sono più persone magari un’oretta e un quarto.
I partecipanti sono stati molto soddisfatti!

**Comment by nicolaiarocci** [comment]
Questo sarebbe ideale da tenere in abbinamento a #32

**Comment by verlok** [comment]
Io son sempre disponibile :)

**Comment by nicolaiarocci** [comment]
Vedi commento in #32 - proviamo a farli nella stessa giornata. Organizziamoci di là.

**Comment by verlok** [comment]
Ecco a voi, per chi c'era e per chi non c'era, le mie slide.
https://docs.google.com/presentation/d/1a9wd_pcQD9V_2eveM68dGOBwaJUC7qkPe6FDLcw5Qis/

**Comment by verlok** [comment]
Ciao a tutti,
mi piacerebbe avere il vostro feedback sul mio talk di ieri sera. 

Si tratta di dare un voto da 1 a 5 e - solo se volete - aggiungere cosa vi è piaciuto e cosa no.

> [Invia il tuo feedback](https://goo.gl/forms/3dVSnMADFh9R8SQy1)

Grazie
