### ISSUE TITLE
Machine Learning per comuni mortali

### ISSUE THREAD

**Issue by drinky78** [DevRomagna/eventi#69]
Ciao a tutti,
ho preparato di recente una pillola da un'oretta sul machine learning, una cosa leggera trattata per essere comprensibile anche ai non addetti, con pochi tecnicismi e alcuni esempi reali.
L'idea della pillola è di chiarire che sia il machine learning, come funziona e dare qualche spunto su come ci si lavora.

**Comment by drinky78** [comment]
@nicolaiarocci puoi mettere le due label "proposta" e "speaker" anche qui?

**Comment by nicolaiarocci** [comment]
Se intanto vuoi postare abstract e tua breve bio ci mettiamo avanti coi lavori.

**Comment by pizar** [comment]
A me interessa molto

**Comment by nicolaiarocci** [comment]
@drinky78 sei ancora disponibile per questo talk?

**Comment by drinky78** [comment]
Ciao @nicolaiarocci , si sono disponibile. Ti mando a breve tutto quello che ti serve.

**Comment by drinky78** [comment]
@nicolaiarocci credi sia possibile anticipare di un giorno e fare il talk mercoledì 18?
Per me sarebbe molto più comodo rispetto al 19, tuttavia in caso non ci siano alternative, posso organizzarmi.

**Comment by nicolaiarocci** [comment]
Dipende da dove facciamo l'incontro :-) Qualcuno è disponibile a ospitarci? Tu di dove sei?

**Comment by Fuminshou** [comment]
Ideato è disponibile, se per @drinky78 è comodo fermarsi in sede dopo il lavoro ;)

**Comment by nicolaiarocci** [comment]
Ok allora facciamo Mercoledì 18 Aprile in Ideato, ore 20.30 come al solito direi (o era 21?). Aspetto abstract e profilo speaker per pubbicare meetup.

**Comment by drinky78** [comment]
@nicolaiarocci ecco abstract e una velocissima bio

> E' giunto il momento di fare un po' di chiarezza in mezzo al caos che ultimamente gira intorno a "intelligenza artificiale", "machine learning", "deep learning" e le altre parolacce di questo genere che affollano la rete. Si sente parlare sempre più di algoritmi intelligenti che fanno cose sempre più strabilianti e in molti pensano che si tratti di una nuova magia nera pronta a divorare il mondo. Di certo nei prossimi anni cambieranno molte cose, ma intanto cominciamo a togliere qualche velo.

> Marco Radossi. Abito a Ravenna a due passi dalla spiaggia che tuttavia frequento solo quando mia moglie e le mie bambine mi trascinano fuori di casa.
Da alcuni anni lavoro in ideato, dove mi diverto sempre di più ad esplorare il mondo del software che evolve e come questo può creare valore per tutti. Un anno fa ho finalmente preso il coraggio a due mani e mi sono iscritto al mio primo corso di machine learning, materia che mi affascina e mi spaventa da tanto tempo. Così ho cominciato un lungo viaggio pieno di meraviglie, codice Python e di milioni di documenti da leggere!

**Comment by nicolaiarocci** [comment]
https://www.meetup.com/it-IT/DevRomagna/events/249113255/

**Comment by Fuminshou** [comment]
@nicolaiarocci è arrivata una mail da meetup che parla dell'incontro di stasera... ma l'incontro è la prossima settimana, mercoledì 18
Possiamo inviare una seconda mail per correggere?

**Comment by nicolaiarocci** [comment]
fatto!

**Comment by drinky78** [comment]
@nicolaiarocci ho fatto una PR con le slide e qualche link

**Comment by nicolaiarocci** [comment]
Grazie Marco
