### ISSUE TITLE
Cqrs/Event Sourcing for real

### ISSUE THREAD

**Issue by ricfrank** [DevRomagna/eventi#70]
Ciao. 

Vorrei proporre una serata per parlare di tematiche relative a Cqrs ed Event Sourcing. 
L'idea è di portare un po di esperienza diretta dato che attualmente in ideato abbiamo dei progetti in produzione che utilizzano questi pattern.

Pensavo di fare una sessione frontale che parte da alcuni concetti teorici fino ad arrivare a vedere l'implementazione di un caso d'uso.

Non farò live coding e il linguaggio che utilizzerò sarà PHP.

**Comment by ricfrank** [comment]
@nicolaiarocci ciao, la proposta è stata accettata ?

**Comment by nicolaiarocci** [comment]
Diciamo che è entrata in classifica 😄 Ora vediamo se vince la gara dei voti, ma è in ottima posizione.

**Comment by ricfrank** [comment]
Ok grazie 👍

**Comment by nicolaiarocci** [comment]
CIao @ricfrank sei ancora disponibile per questo talk?

**Comment by nicolaiarocci** [comment]
@ricfrank dunque?

**Comment by nicolaiarocci** [comment]
Qualcuno è disponibile per tenere questo talk?

**Comment by matiux** [comment]
Se c'è @ricfrank direi che siamo a posto :)
diversamente 2 parole potrei dirle volentieri magari facendo vedere qualche progetto concreto.

**Comment by nicolaiarocci** [comment]
@ricfrank è non pervenuto dal 6.2.2018. Direi che possiamo procedere. @matiux hai la parola :-) Aspetto abstract, un tuo breve profilo, e una data.

**Comment by nicolaiarocci** [comment]
preferibilmente Marzo (a febbraio dovremmo avere elasticsearch con @sensorario)

**Comment by matiux** [comment]
Diamogli un attimo dai, magari dopo il ping che ho fatto qualche minuto fa si fa vivo :D
Diversamente butto giù qualcosa 
Marzo ad ogni modo è ok

**Comment by matiux** [comment]
Unico neo, a differenza di Riccardo non ho materiale/slide pronte. In caso farei qualcosa di più sintetico puntando direttamente al codice.

**Comment by nicolaiarocci** [comment]
tranquillo noi adoriamo il codice :-)

**Comment by ricfrank** [comment]
Ciao. Scusate ma non ricevevo notifiche da GitHub e mi era completamente passato di mente.

Io posso riproporre la stessa serata fatta al pug. 

Introduzione teorica a cqrs/es e demo in PHP con Broadway e Symfony. 

Marzo sarebbe ok. 

Lascio volentieri lo spazio a @matiux oppure possiamo valutare di farlo insieme.

**Comment by nicolaiarocci** [comment]
Ottimo ragazzi, mi piace l'idea che facciate qualcosa insieme. @ricfrank ci può mettere le slide, @matiux il codice. 

Ci serve una location, un abstract, e i profili degli speaker. Proposte?

**Comment by matiux** [comment]
Vado in ansia da prestazione :D
Mi ero proposto per fare da tampone ma sono subito andato a cercarlo :D
Ad ogni modo Riccardo  ha materiale da vendere e codice. Io posso avere qualche progetto meno accademico e più "reale" ma lascio che decida @ricfrank.

Per la location se torna comodo a più persone posso proporre Rimini.

**Comment by DonCallisto** [comment]
Thumbs up per Rimini :stuck_out_tongue_winking_eye:

**Comment by nicolaiarocci** [comment]
A Rimini mi pare non ci siamo mai andati quindi ben venga. Mi serve indirizzo e conferma disponibilità, ovviamente per la data che dobbiamo ancora decidere. Propongo il 21 Marzo, anche se io sarò via per lavoro, per rimanere nella terza settimana del mese come da abitudini.

**Comment by matiux** [comment]
Per me 21 marzo è ok, mi informo per la location (è l'ufficio di un mio cliente) e vi faccio sapere. 

Attendiamo Risposta definitiva di Riccardo per lo speakeraggio!

**Comment by matiux** [comment]
Per la location a Rimini sarebbe più comodo lunedì mercoledì venerdì. Ad esempio mercoledì 20 marzo. Provo a informarmi per questo giorno?

**Comment by nicolaiarocci** [comment]
Si direi che non ci sono problemi a far di mercoledì :-)

**Comment by ricfrank** [comment]
Ok 20 marzo e location

**Comment by matiux** [comment]
Mi informo immediatamente per la disponibilità allora!

**Comment by nicolaiarocci** [comment]
@matiux fammi sapere quando/se hai conferma per location e data

**Comment by matiux** [comment]
@nicolaiarocci dovrei (spero) aver conferma entro oggi. Vi tengo aggiornati

**Comment by matiux** [comment]
Confermo disponibilità stanza a rimini per mercoledì 20 marzo!

**Comment by nicolaiarocci** [comment]
Ok allora ragazzi mi servono:

- Indirizzo, data e ora (20 marzo 019, 20.30?), nome della location
- Abstract
- Profilo di ognuno di voi due speaker

**Comment by matiux** [comment]
L'indirizzo è Viale Principe Amedeo 7 Rimini
l'ufficio è dentro al grattacielo. Magari metterò qualche foto dell'entrata su meetup.
L'orario penso vada bene ma chiederei a @ricfrank
Per lo speakeraggio secondo me Riccardo ha materiale a sufficienza. Al massimo se serve, se c'è tempo, interesse ecc posso mostrare un esempio/caso reale, ma direi che vediamo in corso d'opera. Serve ugualmente il mio profilo?

**Comment by ricfrank** [comment]
Vi mando tutto entro il fine settimana.

**Comment by nicolaiarocci** [comment]
ottimo

**Comment by ricfrank** [comment]
Orario ok.

**Comment by ricfrank** [comment]
Ecco l'abstract

Titolo: CQRS/Event Sourcing for real

Durante la serata parleremo di concetti base su CQRS/ES fino ad arrivare a vedere un caso d'uso.
L'obiettivo è quello di far comprendere le basi dei due pattern e quando sono utili da utilizzare.
Esplorando CQRS/ES, apriremo alcune parentesi sul Domain Driven Design, un approccio per la risoluzione di problemi complessi che pone l'accento sull'evoluzione del modello di dominio e su come tale approccio sia alla base dei 2 pattern.
Il linguaggio utilizzato sarà PHP.

SPEAKER: Riccardo Franconi
Sviluppatore in soisy e partner in ideato. E' interessato principalmente a buone pratiche di programmazione e metodologie agili. Si occupa di sviluppo backend utilizzando tecnologie open source come Symfony. Babbo, music lover, suona chitarra elettrica e ha all’attivo 6 dischi pubblicati.

Matteo Galacci
Sviluppatore back-end freelance e consulente. Appassionato particolarmente all'aspetto architetturale del software. Fotografo pigro, atleta e sedicente cuoco.

**Comment by ricfrank** [comment]
Serve altro?

**Comment by nicolaiarocci** [comment]
@ricfrank ho trovato questo su google immagini (pensavi di sfuggirmi?) che ne dici di farmi una versione per DevRomagna che lo mettiamo come copertina?

![image](https://user-images.githubusercontent.com/512968/51892000-f0035300-23a0-11e9-82e2-87f1b4bdcbe6.png)

**Comment by nicolaiarocci** [comment]
@matiux hai un nome di azienda/campanello da associare all'indirizzo?

**Comment by matiux** [comment]
@nicolaiarocci l'azienda si chiama In Adrias, di fronte all'entrata di Adrias Online (più visibile).
Come dicevo poi metto qualche foto dell'ingresso su meetup e indico anche eventuali zone parcheggiabili.

P.s. Alla fine io e Riccardo ci siamo confrontati e faremo speakeraggio insieme se va bene per tutti.

**Comment by ricfrank** [comment]
@nicolaiarocci questa copertina immagino l'abbia fatta Nicole (o FIlippo) di ideato. Io non sarei mai in grado di fare una cosa cosi bella :D. Posso sentire se hanno voglia di farne una per dev romagna a partire da questa, aggiungendo anche la foto di Matteo. 

@matiux a te andrebbe bene ?

**Comment by nicolaiarocci** [comment]
@ricfrank è che non trovo una immagine decente per CQRS :-) Sentiamo se @Fuminshou fa il miracolo, altrimenti ci piazzo qualcos'altro :-)

**Comment by matiux** [comment]
@ricfrank per me va bene

**Comment by ricfrank** [comment]
@nicolaiarocci questa https://www.meetup.com/it-IT/PUG-Romagna-PHP-User-Group-Romagnolo/events/251487389/?fbclid=IwAR2eDsF_eCYQa8tWVLf1qz046Pjn3QXbOz6k_1wwVzsWn_vOhjSY8ioPy9c ?

**Comment by nicolaiarocci** [comment]
https://www.meetup.com/it-IT/DevRomagna/events/258490013/

Fatto!

**Comment by nicolaiarocci** [comment]
@ricfrank @matiux io sono ancora all'estero e non riesco a rientrare per favore fate la solita introduzione spiegando come fare a proporre talk, votarli, eccetera grazie :-)

**Comment by matiux** [comment]
@nicolaiarocci no problem :)

**Comment by ellenico77** [comment]
serata stra-interessante e ricca di spunti grazie a tutti, in particolare a @ricfrank e @matiux per la disponibilità e la chiarezza nell'esposizione

**Comment by des79** [comment]
Serata molto interessante e argomento molto ben spiegato da @ricfrank e @matiux.  Grazie come sempre anche per l'ospitalità.

**Comment by matiux** [comment]
Grazie a voi! :)

**Comment by ricfrank** [comment]
Grazie mille a voi!!!

**Comment by nicolaiarocci** [comment]
👏 👏 👏

**Comment by matiux** [comment]
@nicolaiarocci ho fatto un PR con il materiale della serata!
