### ISSUE TITLE
elasticsearch for dummies

### ISSUE THREAD

**Issue by sensorario** [DevRomagna/eventi#76]
Dopo poche ore di prove su elasticsearch la mia prima reazione e' stata:

 "perche' ancora oggi si scrivono le api"?

Vorrei condividere con voi la mia piccola esperienza per iniziare a conoscere questo strumento di lavoro.

**Comment by AlessandroMinoccheri** [comment]
Questo mi interessa molto!

**Comment by nicolaiarocci** [comment]
@sensorario che ne dici lo accendiamo? Servono: location, data (febbraio?), abstract, profilo (ma lo posso prendere dai talk precednenti)

**Comment by sensorario** [comment]
Che giorno di Febbraio?

**Comment by nicolaiarocci** [comment]
Giovedì 21?

**Comment by nicolaiarocci** [comment]
@sensorario ti vedo distratto :-)

**Comment by sensorario** [comment]
Sorry, avevo perso la prima notifica =(. Accendiamola!

**Comment by nicolaiarocci** [comment]
@sensorario mi serve abstract. per profilo se non lo vuoi aggiornare uso quello di ultima volta. Immagino sede Mado?

**Comment by sensorario** [comment]
Ok per absrtract e per la sede.

**Comment by nicolaiarocci** [comment]
@sensorario ok da Mado ma mi serve abstract, dai!

**Comment by sensorario** [comment]
Sviluppare API con interfaccia REST. Archiviare i dati per future ricerche temporali su centinaia di migliaia di record nuovi ogni giorno. Costruire una dashboard per interrogare i dati raccolti. Costruire report. Come fare a realizzare tutto questo? Come fare senza dover rompere il salvadanaio usando strumenti eccessivamente costosi? Le risposte a queste domande sono Elasticsearch e Kibana. Open source e gratuiti. Se a questi aggiungiamo AWS e Docker siamo in grado di costruire uno stack tecnologico che puo' stravolgere il modo di progettare applicazioni web, o parte di esse.

puo' andare?

**Comment by nicolaiarocci** [comment]
alla grande, grazie. Quindi riassumendo: 

- Dove: Studio Mado
- Quando: 21.2.2019
- Chi: Simone Gentili

Confermi?

**Comment by sensorario** [comment]
Confermo!

**Comment by nicolaiarocci** [comment]
https://www.meetup.com/it-IT/DevRomagna/events/257990206/

**Comment by nicolaiarocci** [comment]
@sensorario a stasera!

**Comment by sensorario** [comment]
https://github.com/sensorario/docker-elasticsearch
