### ISSUE TITLE
Kanban

### ISSUE THREAD

**Issue by verlok** [DevRomagna/eventi#8]

**Comment by micheleorselli** [comment]
se volete uno speaker eccomi! :-)

**Comment by nicolaiarocci** [comment]
got it!

**Comment by Fuminshou** [comment]
@micheleorselli @nicolaiarocci questa si potrebbe organizzare a marzo, magari a Ravenna?

**Comment by nicolaiarocci** [comment]
Se @micheleorselli c'è per fare da speaker, io sento se riusciamo a organizzare presso Città Attiva.

**Comment by micheleorselli** [comment]
yep, ci sono! Sarebbe carino provare a fare un dot game, che è un gioco per fare capire i principi della kanban. Serve però una superfice tipo dei tavoli a cui la gente può appoggiarsi, @nicolaiarocci lo vedi fattibile?

**Comment by nicolaiarocci** [comment]
@micheleorselli presso Città Attiva ci sono dei tavoli.. un po' traballanti ma ci sono, qualcosa ci inventiamo. Comincio col chiedere disponibilità della sala, per la data direi 19 Aprile ok?

**Comment by Fuminshou** [comment]
Scusa @nicolaiarocci a marzo è previsto un altro evento?
Altrimenti potremmo fare questo a marzo (giovedì 15 sarebbe la data di default, se va bene a tutti)

**Comment by nicolaiarocci** [comment]
@Fuminshou non dovevamo fare i bot a Marzo?

**Comment by nicolaiarocci** [comment]
No scusa, i bot a febbraio. @micheleorselli ti tocca mandarmi un abstract.

**Comment by nicolaiarocci** [comment]
E pure confermarmi la tua disponibilità, scegli tra 15 e 22 Marzo.

**Comment by micheleorselli** [comment]
ok! controllo il calendario e ti faccio sapere a breve

**Comment by micheleorselli** [comment]
15 marzo ok!

Abstract:

Il metodo Kanban (o per gli amici, semplicemente Kanban) è oggi molto utilizzato nel mondo IT, portando benefici in termini di organizzazione del lavoro, riduzione degli sprechi, miglior time to market. In questa sessione vedremo come funziona ma soprattutto, con un gioco di gruppo perchè funziona!

**Comment by nicolaiarocci** [comment]
CittaAttiva non è disponibile il 15 Marzo. Verifico se il fablab di Fornace lo è.

**Comment by Simone-Zabberoni** [comment]
@nicolaiarocci certo, volentieri!

**Comment by nicolaiarocci** [comment]
@Simone-Zabberoni 

- quanti posti sono disponibili?
- proiettore?
- 20.30 - 23.00 va bene come orario?
- indirizzo

Grazie.

**Comment by Simone-Zabberoni** [comment]
@nicolaiarocci: 
- 25/30 persone senza problemi
- c'è il proiettore, mi stò procurando il telo da proiezione
- l'orario è ok
- Ravenna - Via Fratelli Lumière, 46/A (dietro Gamma/Simatica)

@micheleorselli probabilmente martedì sera sono li, fammi un fischio se vuoi passare a vedere i tavoli

**Comment by nicolaiarocci** [comment]
https://www.meetup.com/it-IT/DevRomagna/events/247896848/
