### ISSUE TITLE
Introduzione alla programmazione funzionale per lo sviluppatore OOP

### ISSUE THREAD

**Issue by sensorario** [DevRomagna/eventi#83]
Functional Programming visto dalla prospettiva del programmatore Object Oriented di lungo periodo: cosa, come, e soprattutto perchè. Userò F# e C#/Python come riferimento, ma il taglio è generale e credo possa essere un talk utile indipendentemente dai linguaggi usati negli esempi. 

Speaker: @nicolaiarocci

**Comment by sensorario** [comment]
+6

**Comment by MaxArt2501** [comment]
Daje Nico!

**Comment by matiux** [comment]
Molto interessante!

**Comment by davidedonattini** [comment]
Argomento che mi interessa molto...noi mettiamo a disposizione la nostra sede di Faenza se serve.

**Comment by nicolaiarocci** [comment]
@davidedonattini se ti dico 21 Novembre che mi rispondi? 😄

**Comment by davidedonattini** [comment]
Ok! Andata!

**Comment by nicolaiarocci** [comment]
https://www.meetup.com/it-IT/DevRomagna/events/265866894/
