### ISSUE TITLE
TypeScript: introduzione e casi d'uso

### ISSUE THREAD

**Issue by MaxArt2501** [DevRomagna/eventi#84]
JavaScript con gli steroidi per progetti di ampio respiro. ✌️

**Comment by MaxArt2501** [comment]
Tra parentesi, @nicolaiarocci le etichette "speaker" e "location" è perché hai dato per scontato che già ci fossero disponibili? 😄

In ogni caso sì, è così. Lo dico per conferma 👍

**Comment by nicolaiarocci** [comment]
Esatto Max! Dobbiamo decidere la data e io ti proporrei 11 Aprile per non stare a ridosso di Pasqua e feste varie (ma che ci dobbiamo fare poi con tutte ste feste..)

Mandami abstract intanto, grazie.

**Comment by MaxArt2501** [comment]
Ok, te lo faccio avere non appena avrò deciso bene di cosa parlare 😄

**Comment by MaxArt2501** [comment]
Ciao @nicolaiarocci, purtroppo temo di non farcela per l'11. Riusciamo a fare in un'altra data? O andiamo direttamente per maggio?

Il tuo talk su FP potrebbe pure inserirsi 😉

**Comment by nicolaiarocci** [comment]
@MaxArt2501 il 10 Aprile?

**Comment by MaxArt2501** [comment]
Ehm, no, quel "temo di non farcela per l'11" voleva dire che vorrei che la data fosse più in là nel tempo, non un giorno prima 😅

**Comment by MaxArt2501** [comment]
Ehm, no, quel "temo di non farcela per l'11" vuoleva dire che vorrei che si facesse più in là nel tempo e non un giorno prima 😅
Volevi dire 10 maggio?

**Comment by nicolaiarocci** [comment]
No per maggio ti proporrei il 16 o il 23, che ne dici?

**Comment by MaxArt2501** [comment]
Entrambe vanno benone 👍 
Ti faccio avere presto l'abstract

**Comment by nicolaiarocci** [comment]
ok aspetto

**Comment by nicolaiarocci** [comment]
Sempre da voi in Astreem eh

**Comment by nicolaiarocci** [comment]
@MaxArt2501 come on!

**Comment by MaxArt2501** [comment]
Eccomi! Scusa il ritardo, ero davvero impegnato! 😅

Dalla sua nascita JavaScript è sempre stato un linguaggio debolmente tipizzato, e in un certo senso questo ne ha decretato il successo. Ma col successo e la necessità di scrivere applicazioni front-end e back-end sempre più vaste e complesse si ha avuto la necessità di migliori strumenti per evitare il caos.
Una delle soluzioni è TypeScript, estensione di JavaScript sviluppata da Microsoft, che non solo ci fornisce strumenti tipici della programmazione a oggetti classica, ma anche il supporto alle ultime novità di JavaScript. E anche di più, perché TypeScript non è solo "JavaScript con i tipi"...
Vedremo le basi del linguaggio, le sue peculiarità, esempi concreti di migrazione di codice legacy, best practices e anche un'occhiata all'ecosistema che TypeScript ha creato nel tempo.

**Comment by nicolaiarocci** [comment]
@MaxArt2501 grande Max. Mi confermi disponibilità Astreem per il 23 Maggio, solita ora?

**Comment by MaxArt2501** [comment]
Sì, ma anche il 16 se vuoi 👍

**Comment by nicolaiarocci** [comment]
https://www.meetup.com/it-IT/DevRomagna/events/260307622/

**Comment by marcopollacci** [comment]
Grazie mille a tutti per stasera! Evento decisamente interessante :)
