### ISSUE TITLE
Neo4j GDBMS, un grafo per connetterli tutti

### ISSUE THREAD

**Issue by lucacanella** [DevRomagna/eventi#85]
1. Basi dati a grafo, cosa sono, quali vantaggi e svantaggi hanno rispetto a RDBMS.
2. Neo4j intro.
3. Cypher.
4. Use case, demo.

Per la Demo direi un caso d'uso semplice:
1. Avviamo Neo4j su container docker.
2. Importiamo un csv generando dati sul grafo.
3. Qualche interrogazione (anche complessa).

**Comment by nicolaiarocci** [comment]
Ciao Luca, grazie. Avresti a disposizione anche location per il meetup?

**Comment by lucacanella** [comment]
Ciao Nicola, può darsi, non ci avevo pensato, ma in effetti potrei trovare anche una location. Commento appena ho notizie, ma fino a quel momento procederei come se non l'avessi.

**Comment by davidedonattini** [comment]
Argomento che mi interessa molto...noi mettiamo a disposizione la nostra sede di Faenza se serve.

**Comment by marcopollacci** [comment]
Super interessato pure io!

**Comment by nicolaiarocci** [comment]
@lucacanella se ancora disponibile per tenere questo talk?

**Comment by lucacanella** [comment]
Certo, mi serve il tempo per recuperare ed aggiornare il materiale, però ci sono. Che date ci sarebbero disponibili?

**Comment by nicolaiarocci** [comment]
Se @davidedonattini conferma disponibilità di Studio Mado direi il 20 Febbraio, un giovedì, se a loro va bene.

**Comment by lucacanella** [comment]
Chiedo scusa ma il 20 non son disponibile io. La prima di Marzo sarebbe perfetto

**Comment by nicolaiarocci** [comment]
@lucacanella @davidedonattini il 19 Marzo invece?

**Comment by nicolaiarocci** [comment]
Come non detto il 19 marzo abbiamo già altro talk. Vorrei fare a febbraio per tenere distanza da quello di Marzo. Possibile?

**Comment by lucacanella** [comment]
Possiamo farei il 27? Il 13 ci posso provare ma non sono sicuro di riuscire.

**Comment by davidedonattini** [comment]
Per me il 27 può andare.

**Comment by nicolaiarocci** [comment]
27 marzo, febbraio? Per me va bene. @lucacanella mi serve un abstract e una breve bio tua per fare la scheda su meetup.

**Comment by lucacanella** [comment]
Immaginavo il 27 Febbraio. Per il resto Sabato condivido tutto.

**Comment by nicolaiarocci** [comment]
ok 27 febbraio. aspetto abstract e bio.

**Comment by lucacanella** [comment]
Ecco qua:
**Abstract**

> Si parla sempre più di connected data, big data, data science, machine learning, etc., ed è proprio in questo ambito che negli ultimi anni hanno iniziato a prendere piede i database a grafo. Capiremo quando e perché, tra tutti i modelli di database che sono disponibili ad oggi, impiegare un database a grafo: Ne vedremo i principi fondanti ed il loro funzionamento, ne analizzeremo i vantaggi che portano ai progetti ed al business, ed infine vedremo quali alternative offre il mercato in termini di GDBMS. Lo faremo anche con un esempio pratico, introducendo Neo4J (il più famoso ed utilizzato GraphDBMS) ed implementando un semplice sistema di recommendation solamente tramite query in linguaggio Cypher.

**Bio**

> Laureato in Scienze dell'Informazione presso l'Università di Bologna, sono Business Analyst presso Diennea Srl a Faenza. Sono un professionista nel campo IT da oltre dieci anni avendo ricoperto mansioni da sviluppatore (web, frontend, backend, fullstack, ...) e analista, sia come impiegato che come freelance. Vengo spesso impiegato anche per attività di analisi dati e la mia specialità sono i progetti legati al mondo data science ed alle tecnologie web.

**Comment by nicolaiarocci** [comment]
https://www.meetup.com/it-IT/DevRomagna/events/268686306/

**Comment by nicolaiarocci** [comment]
@lucacanella @davidedonattini ordinanza regionale nei chiarimenti pare confermare che un evento come il nostro si possa tenere questa settimana. Io sarei orientato a confermarlo, voi che ne pensate?

**Comment by nicolaiarocci** [comment]
PS link fornito da Angelo Ghigi su meetup.com: https://www.regione.emilia-romagna.it/notizie/attualita

**Comment by davidedonattini** [comment]
Ciao @nicolaiarocci e @lucacanella purtroppo per direttive da capogruppo dobbiamo annullare l'evento.
Proviamo a ripianificarlo per le prossime settimane.

**Comment by lucacanella** [comment]
Ok, per me basta sapere quando, il materiale è già pronto, avrò il tempo di preparare anche un capitolo bonus. Se dovesse essere un Giovedì di Marzo per ora non ho impegni.

**Comment by nicolaiarocci** [comment]
Ok allora direi che riprogrammarlo ai primi di Marzo a questo punto è rischioso, potremmi essere costretti a ri-riprogrammarlo :-) Per ora teniamolo in standby finchè non si risolve la situazione, anche perchè a fine Marzo abbiamo già altro evento in calendario, tra l'altro sempre da Mado. Se si sblocca tutto lo mettiamo ai primi di Marzo, altrimenti ad Aprile.

**Comment by nicolaiarocci** [comment]
@lucacanella disponibilità a fare una sessione online/virtuale?

**Comment by des79** [comment]
Ciao @nicolaiarocci, ciao a tutti, riporto la mia esperienza che in questi giorni ho seguito i meetup AWS serverless: anche loro hanno cominciato ad organizzarli su twitch ed hanno avuto un numero molto elevato di persone connesse: la settimana passata 100 e ieri 30.
E' interessante farli online e anche accessibile a molte più persone che non sempre hanno possibilità di partecipare dal vivo (visto anche il periodo).
Purtroppo stanno rimandando eventi anche di giugno (WorldDucatiWeek) perché questa situazione sarà più lunga del previsto e non al 3 aprile.

Se si riuscisse ad organizzarli online sarebbe veramente interessante.
Grazie

**Comment by nicolaiarocci** [comment]
@des79 grazie per il feedback. Aspettiamo che ci dice lo speaker ;-)

**Comment by lucacanella** [comment]
Sì, mi serve il tempo di organizzarmi un minimo. Ci sono preferenze/consigli a parte Twitch?

**Comment by nicolaiarocci** [comment]
Pensavo a una roba semplice in particolare Meet di Google (di cui ho account che "dovrebbe" funzionare anche con molti utenti) perchè va anche via browser e solo link di condivisione, senza app da dover installare se non vuoi/puoi.

**Comment by des79** [comment]
@nicolaiarocci se hai account gsuite si può fino a 250 persone. Se hai il basic fino a 100. Se è account semplice google fino a 25 ma devi avere account google per accedere

https://support.google.com/a/answer/7303775?hl=it

**Comment by nicolaiarocci** [comment]
Ho account gsuite, dovrebbe bastare link e fino a 250

**Comment by des79** [comment]
@nicolaiarocci quindi dovresti avere la versione enterprise. Uno spunto che mi permetto di fare è valutare se si vuole tenere la registrazione del meetup per renderla disponibile successivamente per chi non riesce in quell'orario.
Se hai la ver. Enterprise puoi registrarla e renderla disponibile https://support.google.com/meet/answer/9308681?hl=it

**Comment by lucacanella** [comment]
Ok, per sicurezza mi sto organizzando anche per Twitch, ho trovato un tool per fare streaming dello schermo.

**Comment by nicolaiarocci** [comment]
@lucacanella ci saresti anche il prossimo giovedì 26 Febbraio?

**Comment by lucacanella** [comment]
Immaginando intendessi 26 Marzo ti direi di sì. Ore 19:30?

**Comment by nicolaiarocci** [comment]
Si 26 Marzo scusa. Ho il jet lag a scarto mensile 😄 Che ne dici di ore 21 invece? Per dar modo a chi ha famiglia di cenare con comodo.

**Comment by lucacanella** [comment]
Nessun problema, ore 21:00 va bene.
Tornando allo streaming, riusciamo a fare un test prima?

**Comment by nicolaiarocci** [comment]
mandami mail a nicola at nicolaiarocci punto com che ti mando link

**Comment by nicolaiarocci** [comment]
Evento riprogrammato online. RSVP: https://www.meetup.com/it-IT/DevRomagna/events/269579666/

**Comment by nicolaiarocci** [comment]
Il codice è disponibile qui: https://github.com/DevRomagna/eventi/tree/master/26032020-Neo4jGDBMS
