### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by verlok** [DevRomagna/eventi#9]

**Comment by sensorario** [comment]
Se passa questo mi studio GoCD o Jenkins!!!

**Comment by Christian961** [comment]
A me interessa Jenkins, lo uso al lavoro ma non lo conosco dettagliatamente

**Comment by verlok** [comment]
:+1:

**Comment by nicolaiarocci** [comment]
molti progetti OSS usano Travis-CI integrato con GitHub. Si potrebbe aggiungere una sezione su come usare CI con GH... oppure lo mettiamo nel talk sui progetti OSS che forse ha più senso. O in entrambe le sessioni ;-)

**Comment by micheleorselli** [comment]
ho fatto continuous integration sia con jenkins che con travis/parenti, se può interessare un po' di metriale pronto ce l'ho

**Comment by nicolaiarocci** [comment]
@micheleorselli potresti fare lo speaker!

**Comment by nicolaiarocci** [comment]
@micheleorselli se organizziamo questo talk per Settembre, ci sei a far da speaker? In Ideato o elsewhere.

**Comment by micheleorselli** [comment]
@nicolaiarocci yes volentieri! Ma verrò con tenuta estiva eh ;-)

**Comment by nicolaiarocci** [comment]
@micheleorselli mi mandi abstract, location e profilo speaker? 31 agosto come la vedi? Preferisci 21 Settembre?

**Comment by micheleorselli** [comment]
@nicolaiarocci verifico quale delle due date, mi è più comoda e ti faccio sapere a breve! Abstract e profilo te li allego qui ok?

**Comment by nicolaiarocci** [comment]
Ok

**Comment by nicolaiarocci** [comment]
Facciamo il 21 Settembre. Mandami pure abstract etc. che pubblico.

**Comment by nicolaiarocci** [comment]
@micheleorselli abstract e profilo!

**Comment by micheleorselli** [comment]
@nicolaiarocci eccoli! Feedback? Posso aggiustare qualcosa se pensi sia il caso...

Abstract: 
Continuous Integration
per quando ne hai bisogno? "ieri". Quante volte avete sentito questa frase? Se lavorate nell'IT penso parecchie. Rilasciare software in maniera rapida senza sacrificare la qualità però non è semplice: la continuous integration (CI) è un insieme di pratiche che puntano ad automatizzare i processi di sviluppo, riducendo i rischi ed aumentando la fiducia del team nel rilasciare un software di qualità

Alcuni degli argomenti trattati
- principi della continuous integration
- creazione di uno script di build
- scegliere un server di CI: build or buy?
- test automatici
- migrazione dei dati
- automatizzare i deploy

Bio: 
di Ravenna, mi piace la spiaggia, il mare, la piadina spessa un dito. Le lettere S e Z per me hanno lo stesso suono. Tra un weekend e l'altro lavoro come software engineer, ora sono CTO e partner in ideato. Mi interessano vari aspetti del mondo del software <inserire buzzword qui> ma ho il pallino per l'automazione nei processi di sviluppo. Sono coautore di "PHP Best Practices", pubblicato da FAG nel 2012. 

Mi piace raccontare quello che imparo, potete trovare alcuni dei miei talk qui: https://joind.in/user/view/188

**Comment by nicolaiarocci** [comment]
Perfetto!

**Comment by nicolaiarocci** [comment]
Facciamo da voi? Ore 20.30? Cena sociale prima?

**Comment by micheleorselli** [comment]
yes! verifichiamo la disponibilità della sala sotto ma non dovrebbero esserci problemi

**Comment by nicolaiarocci** [comment]
https://www.meetup.com/it-IT/DevRomagna/events/241083496/

**Comment by Fuminshou** [comment]
Hola chicos,
vi aggiorno con novità fresche fresche di stamattina:

1. la sala sotto ideato non è più disponibile, sentirò con i ragazzi di Dinamo Coworking se ci ospitano per una sera.

2. @micheleorselli probabilmente il 21 non ci sarà, chiedeva di spostare la data al giovedì dopo, il 28/09... è fattibile secondo voi?

**Comment by AlessandroMinoccheri** [comment]
1. Se avete problemi fate un fischio che vediamo di organizzarci per un'altra location
2. Per me non ci sono problemi, bisogna aggiornare l'evento su meetup e spammare un pò la gente che aveva aderito magari cosi da avvertirla in anticipo

**Comment by nicolaiarocci** [comment]
Ho parlato con Michele che mi ha avvisato nei giorni scorsi e ho già riprogrammato per il 28.9. Non so se meetup farà mail in automatico con aggiornamento, altrimenti farò a manina. Per la sala mi dice Michele che state cercando, aspetto aggiornamenti. Grazie Nicole.

**Comment by Fuminshou** [comment]
Ragazzi, è confermato che siamo ospitati dal dinamo coworking di cesena (Via Ravennate, 959, 47521 Cesena FC. Piano primo. Accesso dalle scale a lato)
Mi dovrebbero mandare un paragrafo sul cowo da inserire nella descrizione dell'evento, se possibile ;)

**Comment by nicolaiarocci** [comment]
Ottimo appena hai anche il paragrafo aggiorno evento così spammiamo tutti una volta sola 😄.

**Comment by verlok** [comment]
Ciao,
molto interessante questo evento. 

Chiedo: c'è la possiblità che in futuro gli eventi tornino a tenersi più verso ovest? Cesena è un po' fuori mano per noi che confiniamo con l'Emilia. Io avevo iniziato a partecipare anche attivamente a questa community perché gli eventi si tenevano ad Imola, e ci sta che si ruoti un po' a Faenza, un po' a Cesena, un po' a Ravenna, basta che non diventi un'esclusiva di Cesena però ;)

Grazie!

**Comment by Fuminshou** [comment]
Ciao @verlok, l'evento di ottobre è previsto a Ravenna mentre quello di novembre a Faenza (da Studio Mado) quindi puoi stare tranquillo... come hai detto tu, cerchiamo di ruotare tra le città della provincia per far "scomodare" la gente a turni :)

**Comment by verlok** [comment]
Ok allora, è evidente che non mi è chiaro il calendario. Andrò a consultare meetup.com.

**Comment by Fuminshou** [comment]
@nicolaiarocci ecco il paragrafo del Dinamo:

> Dinamo è più di un spazio di lavoro condiviso, è una community di freelance, lavoratori indipendenti, “remote worker” e startup, che condividono valori, scambiano competenze, contatti, si confrontano, si formano e crescono.

Il loro sito, se c'è modo di linkarlo: http://www.dinamocowork.com/
La loro pagina FB: https://www.facebook.com/DinamoCoworkCesena/

Grazie :)

**Comment by verlok** [comment]
Ciao @Fuminshou,
per questo evento purtroppo sono finito nella lista d'attesa di Meetup.com.
I prossimi eventi quando verranno pubblicati là?

**Comment by Fuminshou** [comment]
Ciao @verlok 
meetup lo gestisce @nicolaiarocci ma se non sbaglio sono già stati pubblicati gli eventi di ottobre (https://www.meetup.com/it-IT/DevRomagna/events/240838433/) e novembre (https://www.meetup.com/it-IT/DevRomagna/events/242114775/), per cui ci sono ancora posti disponibili.

Nicola correggimi e integra se ho dimenticato qualcosa!

**Comment by verlok** [comment]
No vabbè hanno seri problemi di UX a meetup.com - la pagina di dettaglio evento sembra una pagina di elenco eventi con un solo evento! Oppure sono io che sono technically disabled (eppure, pigio tasti da oltre 30 anni, non dovrei essere così tonto! Oddio forse ho pigiato quelli sbagliati! 😭)

**Comment by nicolaiarocci** [comment]
@Fuminshou per la cena pre-evento lascio 19.30 davanti a Ideato oppure cambia anche quella?

**Comment by verlok** [comment]
@nicolaiarocci @Fuminshou Ideato è più lontano di Dinamo, Google Maps dice 3 km oltre... se potessimo fare che dopo cena non dobbiamo riprendere l'auto per andare a Dinamo sarebbe il top :)

**Comment by nicolaiarocci** [comment]
Concordo! Quasi quasi farei direttamente incontro da dinamo alle 20.30 con inizio sessione, a meno che non ci sia posto per mangiare qualcosa lì vicino (e un volontario disponibile a gestire la cosa)

**Comment by Fuminshou** [comment]
Si, vicino al Dinamo non ci sono posti adeguati
Io quella sera non sono sicura di esserci perchè il giorno dopo sono a Reggio Emilia quindi per questo giro salterei la cena e partirei direttamente con la serata dalle 20:30

**Comment by nicolaiarocci** [comment]
Ok

**Comment by nicolaiarocci** [comment]
@Fuminshou rimane confermata la capienza max di 30 posti? Domando perchè ci sono persone in lista di attesa e se la nuova location fosse più capiente le potremmo accontentare.

**Comment by Fuminshou** [comment]
Si, la capienza è sempre 30 posti, mi spiace

**Comment by nicolaiarocci** [comment]
https://www.meetup.com/it-IT/preview/DevRomagna/events/241083496
