### ISSUE TITLE
PHP Next Generation: Un nuovo linguaggio di programmazione

### ISSUE THREAD

**Issue by matiux** [DevRomagna/eventi#93]
PHP è un linguaggio di programmazione che soffre di una cattiva nomea. Questo a causa di un passato in cui era un linguaggio indubbiamente meno "performante" e privo di funzionalità rispetto tanti altri concorrenti dei suoi tempi, ma anche a causa di tanto cattivo utilizzo che ne è stato fatto. Tutto ciò ha fatto si che molti programmatori lo abbandonassero, rimanendo ancorati ai pregiudizi della vecchia versione 5 o ancor peggio 4.

Alla fine del 2015 è stato rilasciato PHP 7.0 che, a differenza di tante altre major release, non ha portato solo qualche nuova feature, ma ha portato un nuovo linguaggio di programmazione, dalla sintassi si uguale alle precedenti versione, ma profondamente diverso "under the hood".

Mi piacerebbe raccontare cosa PHP 7.0 ha portato di nuovo, perchè molte grossissime aziende ancora lo usano e ci investono e perchè oggi andrebbe rivalutato in positivo. Senza tralasciare qualche accenno alla nuova release 7.4 uscita a fine 2019.

Disponibile location a Rimini che però tiene al massimo 20 persone (non comodissime)

**Comment by drego85** [comment]
Ottima idea, mi piace!

**Comment by des79** [comment]
Sembra interessante come cosa ma scusa la domanda, forse stupida, a differenza dell'evento di stasera?
Si fa riferimento a cose differenti?
https://www.meetup.com/it-IT/PUG-Romagna-PHP-User-Group-Romagnolo/events/267717151/

Grazie

**Comment by matiux** [comment]
@des79 la differenza con l'evento di stasera è il target.
Stasera ci sarà gente che, in quanto partecipante al PUG, dovrebbe conoscere php e quindi si aspetta aggiornamenti in merito.

Portando invece l'argomento al Dev Romagna spero di dare chiarimenti positivi a chi PHP non lo usa da anni o non lo ha mai usato.

**Comment by nicolaiarocci** [comment]
@matiux avresti anche la location?

**Comment by matiux** [comment]
@nicolaiarocci come dicevo, è disponibile location a Rimini (Adrias Online) che però tiene al massimo 20 persone (non comodissime). Se è prevista più gente potrebbe essere particolarmente scomodo e quindi servirebbe un posto più capiente.

**Comment by nicolaiarocci** [comment]
@MaxArt2501 Arteem potrebbe ospitarci?

**Comment by matiux** [comment]
@nicolaiarocci stai pensando a Imola?
Diciamo che se siamo nel triangolo Faenza, Ravenna, Rimini vado meglio, ma vediamo.

**Comment by theMiddleBlue** [comment]
Interessante, saresti disponibile a farlo in live su YouTube con un focus sulla sicurezza?

**Comment by matiux** [comment]
@theMiddleBlue la sicurezza sarebbe da approfondire in un evento dedicato e probabilmente con un sistemista / devops.
Posso provare a organizzare anche qualcosa  in merito, ma per ora, la serata che ho in mente non tratterà questo aspetto.

**Comment by drego85** [comment]
@matiux mi intrometto perché il commento di @theMiddleBlue deriva indubbiamente dal mio [tweeet odierno](https://twitter.com/AndreaDraghetti/status/1225696640847114242).

The Middle possiede un noto canale YouTube sull'ITSec e probabilmente ti chiede se è possibile fare un video/live dedicato alla sicurezza di PHP74. Sicuramente una cosa "sgangiata" da questo evento per DevRomagna e quindi credo che siamo offtopic. 😬 Sorry!

**Comment by theMiddleBlue** [comment]
confermo il referrer dal tweet di @drego85 :) scusate l'offtopic. @matiux nel caso continuiamo la conversazione in privato.

**Comment by MaxArt2501** [comment]
@nicolaiarocci Direi che non ci sono problemi, data permettendo. C'è già un'indicazione?

**Comment by matiux** [comment]
@MaxArt2501 dove sarebbe la location? Imola?

**Comment by matiux** [comment]
@theMiddleBlue @drego85 in caso parliamone

**Comment by MaxArt2501** [comment]
Sì, siamo ad Imola, torre nera all'uscita dell'autostrada.
Capisco che siamo un po' al confine della Romagna, ma magari si acchiappa qualcuno della scena bolognese.

**Comment by matiux** [comment]
Come dicevo sopra, non mi rimane molto comodo da Cervia. Alternative?
Se siamo sulla 20ina di persone a Rimini c'è disponibilità, oppure posso sentire a Faenza.

**Comment by nicolaiarocci** [comment]
Proponevo Imola anche perchè se ho ben capito si è parlato di PHP 7 a Rimini l'altra sera :-) Faenza va anche bene, almeno rimescoliamo un po' le carte.

**Comment by matiux** [comment]
@nicolaiarocci si è corretto e in effetti non hai tutti i torti. 
Proviamo Faenza?
Posso informarmi io per la location

**Comment by nicolaiarocci** [comment]
ok. @MaxArt2501 saremo da Antreem alla occasione successiva.

**Comment by marcopollacci** [comment]
Se per qualsiasi caso si dovesse rispostare ad Imola, interessatissimo.
Macino php tutti i giorni, ma è sempre bellissimo sentire altri esperti :)

**Comment by matiux** [comment]
@marcopollacci Faenza Imola non sono molto distanti. Se fosse Faenza andrebbe bene?

Poi se a Faenza non c'è posto vedo di fare un sacrificio eheh

**Comment by marcopollacci** [comment]
Sì, vero,..a sto punto un po' è la discriminante è l'orario ed il giorno vediamo un po' :)..intanto seguo!

**Comment by nicolaiarocci** [comment]
@matiux siamo in standby per location a Faenza, con Antreem/Imola come backup.

**Comment by matiux** [comment]
@nicolaiarocci a Faenza Studio Mado da disponibilità.
Quindi ora rimane da decidere il giorno.

Il lunedì è il giorno della settimana dove riesco meglio

**Comment by nicolaiarocci** [comment]
Con Febbraio e Marzo già presi, direi Aprile. Per rimanere nella tradizione del terzo giovedì del mese proporrei Giovedì 16 Aprile. Da verificare anche con i ragazzi di Mado la loro disponibilità. Che ne dici @matiux

**Comment by matiux** [comment]
@nicolaiarocci mi spiace ma allora come non detto, il giovedì ho un impegno fisso.

**Comment by nicolaiarocci** [comment]
Beh siamo anche capaci di flessibilità 😄 Lunedì 20 Aprile?

**Comment by matiux** [comment]
ciao @nicolaiarocci, lunedì 20 aprile per me è ok.
Sento Studio Mado se da disponibilità per quella sera ok?

**Comment by nicolaiarocci** [comment]
ok

**Comment by matiux** [comment]
@nicolaiarocci Studio Mado da disponibilità per il lunedì 20 aprile

**Comment by nicolaiarocci** [comment]
ok accendiamolo. Abstract e bio?

**Comment by matiux** [comment]
@nicolaiarocci entro i primi della prossima settimana ti mando tutto.

**Comment by matiux** [comment]
@nicolaiarocci 

**Abstract**

> PHP è un linguaggio di programmazione che, tra chi non lo usa, soffre di una cattiva nomea. Questo a causa di un passato in cui era un linguaggio indubbiamente meno "performante" e privo di funzionalità rispetto tanti altri concorrenti dei suoi tempi, ma anche a causa di tanto cattivo utilizzo che ne è stato fatto. Tutto ciò ha fatto si che molti programmatori lo abbandonassero, rimanendo ancorati ai pregiudizi della vecchia versione 5 o ancor peggio 4.
> 
> Alla fine del 2015 è stato rilasciato PHP 7.0 che, a differenza di tante altre major release, non ha portato solo nuove features, ma si è trasformato in un nuovo linguaggio di programmazione, dalla sintassi si uguale alle precedenti versione, ma profondamente diverso "under the hood".
> 
> Mi piacerebbe raccontare cosa PHP 7.0 ha portato di nuovo, perchè molte grossisse aziende ancora lo usano e ci investono e perchè oggi andrebbe rivalutato in positivo.
> Vedremo anche cosa php 7.4, uscito a fine 2019, ha portato di nuovo.

**Bio**

> Mi chiamo Matteo Galacci. Lavoro come consulente da 12 anni occupandomi di architettura software e sviluppo back-end. Applico e divulgo, tramite consulenza e formazione, principi sul codice pulito e la manutenibilità del software a lungo termine cercando di sensibilizzare i programmatori su come il codice debba seguire il dominio aziendale piuttosto che framework o approcci vendor lock-in. Domain Driven Design addicted.

**Comment by MaxArt2501** [comment]
Non vorrei fare il guastafeste, ma siamo sicuri che venga permesso di fare il meetup? Dico per via delle direttive sanitarie regionali.

**Comment by Danysan1** [comment]
La direttiva attuale dura fino al 1 Marzo. Si era parlato di svolgere il Meetup il 20 Aprile, speriamo che per quella data non ci siano più direttive di questo genere (o meglio, speriamo sia passata la necessità di avere direttive di questo genere!)

Ad ogni modo attualmente è troppo presto per sapere quale sarà la situazione in quella data

**Comment by matiux** [comment]
@nicolaiarocci c'è ancora interesse per questo talk? Magari fatto online

**Comment by nicolaiarocci** [comment]
Certo @matiux, quando saresti disponibile? Lo facciamo online.

**Comment by matiux** [comment]
@nicolaiarocci il talk è fondamentalmente pronto, quindi non mi serve molto tempo per prepararmi/lo, giusto una spolverata. in che mese vorresti farlo?

**Comment by nicolaiarocci** [comment]
anche settimana prossima. c'è altro talk in ballo per Maggio il primo che si prenota vince lo slot :-)

**Comment by matiux** [comment]
@nicolaiarocci potrebbe andare mercoledì 27 ?

**Comment by nicolaiarocci** [comment]
Ciao @matiux scusa ero via e ho visto solo ora. Per dar tempo a tutti di organizzarsi proporrei il mercoledì successivo 3 Giugno.

**Comment by matiux** [comment]
ciao @nicolaiarocci direi che è ok

**Comment by nicolaiarocci** [comment]
https://www.meetup.com/it-IT/DevRomagna/events/270877741/

**Comment by nicolaiarocci** [comment]
Riprogrammato per il 10 Giugno per evitare sovrapposizione con evento del PUG.

**Comment by drego85** [comment]
Ciao,
se può interessare per pubblicarlo sui vostri canali ho lo screencast del talk.

**Comment by nicolaiarocci** [comment]
@drego85 ciao Andrea, grazie. Se hai un link lo condividiamo assieme al materiale.

**Comment by drego85** [comment]
Ho caricato provvisoriamente il video, grezzo, [qui](https://mega.nz/file/NQNSiYqI#jqq_XF1640jWG3N-6-xVKHvNIdRBiIjIP7BD2Q5PsyA)!

Eventualmente sarebbe da tagliare per eliminare le parti futili all'inizio e alla fine.

**Comment by matiux** [comment]
@drego85 grazie :)

**Comment by matiux** [comment]
@nicolaiarocci potrebbe avere senso tagliarlo e caricarlo su youtube? esiste un canale dev romagna?

**Comment by nicolaiarocci** [comment]
no non esiste. se qualcuno ha tempo e voglia di editarlo, sarebbe ottimo.

**Comment by matiux** [comment]
Magari creare il canale youtube è una cosa veloce.
Per quanto riguarda l'editing non saprei. @drego85 tu hai esperienza in merito?

**Comment by drego85** [comment]
Pochissima esperienza, ma se create un account YouTube ufficiale di Dev Romagna (che potrebbe avere un senso per altri aventi registrati) è possibile direttamente dall'editor video di YouTube andare a ritagliare le parti inutili.

**Comment by matiux** [comment]
@nicolaiarocci che ne dici?

**Comment by nicolaiarocci** [comment]
Sì, mantengo un canale YT per una associazione, so come fare, ma vi confesso che sono perplesso. 

Non sono molto a favore delle registrazioni per il semplice motivo che disincentivano la partecipazione all'evento,  soprattutto nel caso delle sessioni in presenza - che al momento sono sospese certo, ma si spera di poterle riprendere un giorno. Inoltre la registrazione delle sessioni non è scontata: in questo caso abbiamo avuto chi l'ha registrata, ma se torniamo in presenza sarà dura poterla avere. Aprire un canale per pubblicare poi solo 1-2 video all'anno ne vale la pena? Per questo evento abbiamo comunque messo a disposizione il video. Infine, gestire il canale e pubblicare le eventuali registrazioni comporta lavoro e in questo periodo non penso di avere la banda necessaria per prenderlo in carico. Direi che per ora va bene continuare con la pubblicazione di slide e materali chi vuole assistere alla sessione fa il piccolo sforzo di liberarsi e... partecipare! In fin dei conti nasciamo anche e soprattutto come community, e non c'è niente di meno sociale che assistere da soli alla registrazione di un video su YouTube :-)
