### ISSUE TITLE
PureScript: 0 to 2048 

### ISSUE THREAD

**Issue by gcsolaroli** [DevRomagna/eventi#98]
Partire da zero ed arrivare ad una versione giocabile di 2048 in due ore imparando un nuovo linguaggio.

PureScript è un linguaggio funzionale (fortemente ispirato ad Haskell) in grado di produrre (fra varie altre opzioni) JavaScript direttamente eseguibile nel browser: https://www.purescript.org

2048 è un gioco, molto semplice ma estremamente piacevole: https://en.wikipedia.org/wiki/2048_(video_game)

**Comment by nicolaiarocci** [comment]
@gcsolaroli che ne dici di programmarlo per il 10 o 17 settembre?

**Comment by gcsolaroli** [comment]
Chiedo scusa, ma mi sono completamente dormito (la notifica con) la risposta di @nicolaiarocci.

**Comment by nicolaiarocci** [comment]
No problem. 1 Ottobre? Mi servono un abstract e una bio.

**Comment by gcsolaroli** [comment]
Aggiudicato per il primo Ottobre; si va online, vero?
Per quanto riguarda l'abstract spero basti il contenuto del ticket (altrimenti vedo di impegnarmi un po' di più).
Per la bio invece … 
Sono uno sviluppatore "full-stack" con esperienza piuttosto estesa sia nelle tecnologie di sviluppo che negli ambiti operativi.
Ho fatto diverse esperienze lavorative (anche all'estero - Svizzera, USA, Irlanda); il progetto più "interessante" rimane Clipperz (online password manager ancora attivo).
Adesso faccio il responsabile IT in una azienda del settore energetico, ma continuo a gestire direttamente lo sviluppo di diversi strumenti interni.
Sto anche cercando di aiutare altre persone a costruire il proprio percorso in ambito tecnologico; sono stato fra i fondatori del MakerStation FabLab a Cotignola (http://www.makerstation.it) e ultimamente collaboro alla gestione degli eventi MeetLambda (https://twitter.com/meetlambda), dove si approfondiscono gli aspetti di programmazione funzionale.


Può bastare?
